name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u $ --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image and push it to GHCR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.GHCR_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Override ArgoCD Application tag with the newly pushed GHCR tag
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.2.1
          command: app set ${{ vars.ARGOCD_APP_NAME }} -p image.tag=${{ github.sha }}
          options: |
            --server ${{ secrets.ARGOCD_SERVER_URL }}
            --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }}